[theme]
base = "light"
primaryColor = "#2e6da4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f9fc"
textColor = "#222222"
font = "sans serif"
baseFontSize = 24


[server]
maxMessageSize = 500

